package BESA.World.agents.ExternalComm;

public enum ExternalCommMessageType {
    NOTIFY_CROP_DISEASE,
    NOTIFY_CROP_WATER_STRESS,
    CROP_INFORMATION_NOTIFICATION,
    NOTIFY_CROP_READY_HARVEST,
    REQUEST_CROP_INFORMATION
}
